version: 2
registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: "${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}"
  npm-registry-library-freightlab-io:
    type: npm-registry
    url: https://library.freightlab.io
    token: "${{secrets.NPM_REGISTRY_LIBRARY_FREIGHTLAB_IO_TOKEN}}"
  npm-registry-verdaccio-forto-io:
    type: npm-registry
    url: https://verdaccio.forto.io
    token: "${{secrets.NPM_REGISTRY_VERDACCIO_FORTO_IO_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "01:00"
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 100
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: fp-ts
    versions:
    - 2.10.4
  registries:
  - npm-registry-registry-npmjs-org
  - npm-registry-library-freightlab-io
  - npm-registry-verdaccio-forto-io
